name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Find and Build Project
      run: |
        PROJ_DIR=$(find . -maxdepth 2 -name "build.gradle.kts" -exec dirname {} \;)
        echo "Building in $PROJ_DIR"
        cd $PROJ_DIR
        gradle assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: "**/app/build/outputs/apk/debug/*.apk"
        
